name: DependentProject
description: ''
version: 1.0.3
author: ashvjit@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: dependentproject
  parentArtefactID: ashvjitprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-12-20 08:02:50'
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/DependentJob:
    name: DependentJob
    description: ''
    fabricUID: 17
    scheduler:
      MWAA: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2023-12-20 08:02:50'
    author: ashvjit@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-12-20 08:02:50'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions:
    airflowFunctions/empower_me:
      name: empower_me
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: ashvjit@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    airflowFunctions/empower_me_more:
      name: empower_me_more
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: ashvjit@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
